spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MySQL_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 20
      maxLifetime: 295000
      poolName: HikariCP
      readOnly: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

server:
  tomcat:
    threads:
      max: 18
      min-spare: 18
    accept-count: 300
  port: 8080

jwt:
  secretKey: ${secret_key}
  refreshKey: ${refresh_key}
